"""changes to the db regarding fk

Revision ID: e889bdd9aa8b
Revises: 9342039c669c
Create Date: 2025-08-04 19:13:03.564762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e889bdd9aa8b'
down_revision: Union[str, Sequence[str], None] = '9342039c669c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('authors_courses_course_id_fkey'), 'authors_courses', type_='foreignkey')
    op.drop_constraint(op.f('authors_courses_author_id_fkey'), 'authors_courses', type_='foreignkey')
    op.create_foreign_key(None, 'authors_courses', 'authors', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'authors_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.add_column('courses', sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('courses', sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('courses', 'duration',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint(op.f('courses_difficulty_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'course_difficulties', ['difficulty_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_difficulty_id_fkey'), 'courses', 'course_difficulties', ['difficulty_id'], ['id'])
    op.alter_column('courses', 'duration',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('courses', 'original_price')
    op.drop_column('courses', 'current_price')
    op.drop_constraint(None, 'authors_courses', type_='foreignkey')
    op.drop_constraint(None, 'authors_courses', type_='foreignkey')
    op.create_foreign_key(op.f('authors_courses_author_id_fkey'), 'authors_courses', 'authors', ['author_id'], ['id'])
    op.create_foreign_key(op.f('authors_courses_course_id_fkey'), 'authors_courses', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###
