FROM mcr.microsoft.com/playwright/python:v1.44.0-jammy

WORKDIR /backend

COPY entrypoint.sh .
RUN sed -i 's/\r$//g' entrypoint.sh
RUN chmod +x entrypoint.sh

# whole codebase better if errors
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENTRYPOINT ["./entrypoint.sh"]
